// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLiNxmraWsqmDFuZSPaP4YlLOt-HaEWr0',
    appId: '1:473187107248:web:35592d00ba176c70c61675',
    messagingSenderId: '473187107248',
    projectId: 'fady-notes',
    authDomain: 'fady-notes.firebaseapp.com',
    storageBucket: 'fady-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwWZ9MmB19_PQOCY7Zuj08cnnOzACmzKE',
    appId: '1:473187107248:android:21684e3eb80f62e5c61675',
    messagingSenderId: '473187107248',
    projectId: 'fady-notes',
    storageBucket: 'fady-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-4Hl-WmLcJuLf3b8ioUVDF0OAW3HnrY',
    appId: '1:473187107248:ios:339bcc0a2b61fa75c61675',
    messagingSenderId: '473187107248',
    projectId: 'fady-notes',
    storageBucket: 'fady-notes.appspot.com',
    iosBundleId: 'com.fadyfawzy.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK-4Hl-WmLcJuLf3b8ioUVDF0OAW3HnrY',
    appId: '1:473187107248:ios:78b91d03bb34f712c61675',
    messagingSenderId: '473187107248',
    projectId: 'fady-notes',
    storageBucket: 'fady-notes.appspot.com',
    iosBundleId: 'com.fadyfawzy.notes.RunnerTests',
  );
}
